name: Benchmarking
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
  pull-requests: read

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

  benchmark:
    runs-on: ubuntu-latest
    env:
      BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
    steps:

       #
       # Check for '/benchmark' comments on a PR
       #
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/benchmark'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      #
      # Extract the branch of that the PR the comment was added to belongs to
      #
      - uses: xt0rted/pull-request-comment-branch@v1
        if: steps.check.outputs.triggered == 'true'
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      #
      # Trigger the buildkite pipeline IF the 'benchmark' command was found
      #
      - run: |
         if [ -z "$BUILDKITE_API_ACCESS_TOKEN" ] ; then
            echo "[trigger-buildkite]: 'BUILDKITE_API_ACCESS_TOKEN' is not set!"
            exit 1
         fi

         echo "[trigger-buildkite]: Triggering build for $PR_BRANCH"

         curl --silent -H "Authorization: Bearer $BUILDKITE_API_ACCESS_TOKEN" \
              "https://api.buildkite.com/v2/organizations/input-output-hk/pipelines/plutus-benchmark/builds" \
              -X "POST" \
              -F "commit=HEAD" \
              -F "branch=${{ steps.comment-branch.outputs.head_ref }}" \
              -F "message=benchmark" > response.json

         export WEB_URL=$(jq -r ".jobs[0].web_url" response.json)
         echo "WEB_URL=$WEB_URL" >> $GITHUB_ENV
        if: steps.check.outputs.triggered == 'true'
